sudo: required

language: node_js

before_install:
  - npm i -g yarn

node_js:
  - "10"
  - "11"

before_script:
  - yarn install

script:
  - yarn run lint
  - yarn run build
  - yarn run test
  
cache:
  yarn: true